USE [master]
GO

/****** Object:  Database [StegDB]    Script Date: 9/1/2026 12:26:06 PM ******/
CREATE DATABASE [StegDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'StegDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL17.MSSQLSERVER\MSSQL\DATA\StegDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'StegDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL17.MSSQLSERVER\MSSQL\DATA\StegDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [StegDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [StegDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [StegDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [StegDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [StegDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [StegDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [StegDB] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [StegDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [StegDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [StegDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [StegDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [StegDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [StegDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [StegDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [StegDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [StegDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [StegDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [StegDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [StegDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [StegDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [StegDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [StegDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [StegDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [StegDB] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [StegDB] SET  MULTI_USER 
GO

ALTER DATABASE [StegDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [StegDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [StegDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [StegDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [StegDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [StegDB] SET OPTIMIZED_LOCKING = OFF 
GO

ALTER DATABASE [StegDB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [StegDB] SET QUERY_STORE = ON
GO

ALTER DATABASE [StegDB] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [StegDB] SET  READ_WRITE 
GO

