"""Groq SQL Generator module — 4-model sequential fallback chain.

Translates natural language admin questions into T-SQL queries.
Tries each model in MODEL_CHAIN in order; falls back to a local
keyword-matcher if all API calls fail.
"""
import json
import logging
import re
import urllib.request
from typing import Optional

from chatbot.config import MODEL_CHAIN
from chatbot.prompts import SYSTEM_PROMPT_TEXT_TO_SQL

logger = logging.getLogger("invoiceflow.chatbot.sql_generator")


# ── Generic single-model caller ───────────────────────────────────────────────

def _call_api(model_cfg: dict, messages: list, temperature: float, max_tokens: int) -> Optional[str]:
    """Call one model endpoint and return the text content, or None on failure."""
    payload = {
        "model": model_cfg["model_id"],
        "messages": messages,
        "temperature": temperature,
        "max_tokens": max_tokens,
    }
    headers = {
        "Content-Type": "application/json",
        "Authorization": f"Bearer {model_cfg['api_key']}",
    }
    headers.update(model_cfg.get("extra_headers", {}))

    req = urllib.request.Request(
        model_cfg["url"],
        data=json.dumps(payload).encode("utf-8"),
        headers=headers,
        method="POST",
    )
    with urllib.request.urlopen(req, timeout=15) as resp:
        if resp.status == 200:
            res_json = json.loads(resp.read().decode("utf-8"))
            choices = res_json.get("choices", [])
            if choices:
                return choices[0].get("message", {}).get("content", "")
    return None


# ── Public entry point ────────────────────────────────────────────────────────

def generate_sql(user_question: str) -> tuple[str, str]:
    """Convert user question into T-SQL.

    Returns:
        (sql_string, model_name_used) — model_name_used is the human-readable
        label of whichever model succeeded, or 'Local Fallback' if none did.
    """
    messages = [
        {"role": "system", "content": SYSTEM_PROMPT_TEXT_TO_SQL},
        {"role": "user", "content": f"USER QUESTION:\n{user_question}"},
    ]

    for model_cfg in MODEL_CHAIN:
        try:
            raw = _call_api(model_cfg, messages, temperature=0.1, max_tokens=1000)
            if raw:
                logger.info("SQL generated by %s", model_cfg["name"])
                return _clean_sql_string(raw), model_cfg["name"]
        except Exception as err:
            logger.warning(
                "Model '%s' failed for SQL generation, trying next: %s",
                model_cfg["name"], err,
            )

    # All API models failed → local keyword matcher
    logger.error("All API models failed; using local keyword-matching fallback.")
    return _fallback_generate_sql(user_question), "Local Fallback"


# ── Helpers ───────────────────────────────────────────────────────────────────

def _clean_sql_string(raw_sql: str) -> str:
    """Extract raw SQL from markdown code blocks if present."""
    cleaned = raw_sql.strip()
    match = re.search(r"```(?:sql)?\s*(.*?)\s*```", cleaned, re.DOTALL | re.IGNORECASE)
    if match:
        cleaned = match.group(1)
    return cleaned.strip().rstrip(";")


def _fallback_generate_sql(user_question: str) -> str:
    """Built-in T-SQL keyword-matching fallback — no API required."""
    q = user_question.lower()

    if any(k in q for k in ["total", "sum", "aggregate"]) or ("duplicate" in q and "invoice" in q):
        return (
            "SELECT COUNT(DISTINCT invoice_no) AS total_unique_invoices, "
            "SUM(net_a_payer) AS total_net_a_payer "
            "FROM (SELECT invoice_no, MAX(net_a_payer) AS net_a_payer FROM Invoices WHERE net_a_payer IS NOT NULL GROUP BY invoice_no) AS sub"
        )
    elif any(k in q for k in ["admin info", "admin informations", "audit", "system log", "history", "log"]):
        return (
            "SELECT TOP 15 a.audit_id, a.action, u.full_name AS actor_name, a.field_changed, "
            "a.old_value, a.new_value, a.timestamp "
            "FROM AuditLogs a "
            "JOIN Users u ON a.actor_id = u.user_id "
            "ORDER BY a.timestamp DESC"
        )
    elif any(k in q for k in ["user", "account", "role", "registered"]):
        return (
            "SELECT u.user_id, u.full_name, u.email, u.role, u.account_status, u.created_at, "
            "COUNT(i.invoice_id) AS total_invoices "
            "FROM Users u "
            "LEFT JOIN Invoices i ON u.user_id = i.user_id "
            "GROUP BY u.user_id, u.full_name, u.email, u.role, u.account_status, u.created_at "
            "ORDER BY u.created_at DESC"
        )
    elif any(k in q for k in ["invoice", "facture", "kwh", "net_a_payer", "amount"]):
        return (
            "SELECT i.invoice_id, u.full_name AS owner_name, i.supplier, i.invoice_no, "
            "i.amount_excl_tax, i.kwh_consumed, i.net_a_payer, i.status, i.uploaded_at "
            "FROM Invoices i "
            "JOIN Users u ON i.user_id = u.user_id "
            "ORDER BY i.uploaded_at DESC"
        )
    elif any(k in q for k in ["demand", "demande", "pending"]):
        return (
            "SELECT d.demand_id, u.full_name AS requester_name, i.invoice_no, i.net_a_payer, "
            "d.status, d.submitted_at "
            "FROM Demands d "
            "JOIN Users u ON d.user_id = u.user_id "
            "JOIN Invoices i ON d.invoice_id = i.invoice_id "
            "ORDER BY d.submitted_at DESC"
        )
    else:
        return (
            "SELECT u.user_id, u.full_name, u.email, u.role, u.account_status, u.created_at "
            "FROM Users u ORDER BY u.created_at DESC"
        )
